apiVersion: v1
kind: Service
metadata:
  name: investment-service
  namespace: nexapay
  labels:
    app: investment-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4005"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4005
      targetPort: http
      protocol: TCP
  selector:
    app: investment-service
