apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: nexapay
  labels:
    app: loan-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4004"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4004
      targetPort: http
      protocol: TCP
  selector:
    app: loan-service
