server.name: "nexapay-kibana"
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]

elasticsearch.username: "kibana_system"
elasticsearch.password: "nexapay_kibana_pass"

xpack.security.enabled: true

xpack.encryptedSavedObjects.encryptionKey: "0123456789abcdef0123456789abcdef"

xpack.reporting:
  enabled: true
  encryptionKey: "0123456789abcdef0123456789abcdef"
  roles:
    enabled: false

xpack.alerting.enabled: true

monitoring.ui.container.elasticsearch.enabled: true

logging:
  root:
    level: info
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json

server.publicBaseUrl: "http://localhost:5601"

i18n.locale: "en"

newsfeed.enabled: false

telemetry.enabled: false

map.includeElasticMapsService: false
