apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: nexapay
  labels:
    app: fraud-detection-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4008"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4008
      targetPort: http
      protocol: TCP
  selector:
    app: fraud-detection-service
