apiVersion: v1
kind: Service
metadata:
  name: user-kyc-service
  namespace: nexapay
  labels:
    app: user-kyc-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4002"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4002
      targetPort: http
      protocol: TCP
  selector:
    app: user-kyc-service
