apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexapay-secrets
  namespace: nexapay
  labels:
    app: nexapay
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: nexapay-secrets
      namespace: nexapay
      labels:
        app: nexapay
    type: Opaque
    data:
      auth-database-url: ""
      auth-redis-url: ""
      user-database-url: ""
      user-mongo-url: ""
      wallet-database-url: ""
      wallet-redis-url: ""
      loan-database-url: ""
      loan-redis-url: ""
      investment-mongo-url: ""
      investment-redis-url: ""
      notification-mongo-url: ""
      notification-redis-url: ""
      reporting-mysql-url: ""
      reporting-es-url: ""
      fraud-redis-url: ""
      jwt-access-secret: ""
      jwt-refresh-secret: ""
      encryption-key: ""
      aws-access-key-id: ""
      aws-secret-access-key: ""
      sendgrid-api-key: ""
      twilio-account-sid: ""
      twilio-auth-token: ""
      smtp-pass: ""
      postgres-password: ""
      mysql-password: ""
      mongo-password: ""
      redis-password: ""
      kafka-password: ""
  encryptedData:
    auth-database-url: "AgAAABBBCCC..."
    auth-redis-url: "AgAAABBBCCC..."
    user-database-url: "AgAAABBBCCC..."
    user-mongo-url: "AgAAABBBCCC..."
    wallet-database-url: "AgAAABBBCCC..."
    wallet-redis-url: "AgAAABBBCCC..."
    loan-database-url: "AgAAABBBCCC..."
    loan-redis-url: "AgAAABBBCCC..."
    investment-mongo-url: "AgAAABBBCCC..."
    investment-redis-url: "AgAAABBBCCC..."
    notification-mongo-url: "AgAAABBBCCC..."
    notification-redis-url: "AgAAABBBCCC..."
    reporting-mysql-url: "AgAAABBBCCC..."
    reporting-es-url: "AgAAABBBCCC..."
    fraud-redis-url: "AgAAABBBCCC..."
    jwt-access-secret: "AgAAABBBCCC..."
    jwt-refresh-secret: "AgAAABBBCCC..."
    encryption-key: "AgAAABBBCCC..."
    aws-access-key-id: "AgAAABBBCCC..."
    aws-secret-access-key: "AgAAABBBCCC..."
    sendgrid-api-key: "AgAAABBBCCC..."
    twilio-account-sid: "AgAAABBBCCC..."
    twilio-auth-token: "AgAAABBBCCC..."
    smtp-pass: "AgAAABBBCCC..."
    postgres-password: "AgAAABBBCCC..."
    mysql-password: "AgAAABBBCCC..."
    mongo-password: "AgAAABBBCCC..."
    redis-password: "AgAAABBBCCC..."
    kafka-password: "AgAAABBBCCC..."
