apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: nexapay
  labels:
    app: wallet-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4003"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4003
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
  selector:
    app: wallet-service
